import ROOT as root
import pickle
import numpy as np
import sys
import pandas as pd

#case = sys.argv[1]

#load root files
infileroot = root.TFile.Open('signal/AnalysisResults.root')
#treegen    = infileroot.Get('MCanalysis/TreeGenOmegaccc')
treecutvar = infileroot.Get('MCanalysis/TreeCutVarOmegaccc')

infileroot_bkg = root.TFile.Open('background/AnalysisResults.root')
treecutvar_bkg = infileroot_bkg.Get('MCanalysis/TreeCutVarOmegaccc')


#check vars
root.gStyle.SetPadLeftMargin(0.15)
root.gStyle.SetPadTickX(1)
root.gStyle.SetPadTickY(1)

hvarscuts = []
hvarscuts.append(root.TH1F('h_inv_mass_omegaccc',';inv_mass_omegaccc',1000,4.,6.))
hvarscuts.append(root.TH1F('h_cos_p_omegaccc',';cos_p_omegaccc',1000,-1,1.))
hvarscuts.append(root.TH1F('h_cos_p_xy_omegaccc',';cos_p_xy_omegaccc',1000,-1.,1.))
hvarscuts.append(root.TH1F('h_decay_length_omegaccc',';decay_length_omegaccc',1000,0.,10.))
hvarscuts.append(root.TH1F('h_decay_length_xy_omegaccc',';decay_length_xy_omegaccc',1000,0.,10.))
hvarscuts.append(root.TH1F('h_chi2ndf_omegaccc',';chi2ndf_omegaccc',1000,0.,20.))
hvarscuts.append(root.TH1F('h_d0_omegaccc',';d0_omegaccc',1000,-1,1.))
hvarscuts.append(root.TH1F('h_pt_omegaccc',';pt_omegaccc',1000,0.,20.))
hvarscuts.append(root.TH1F('h_eta_omegaccc',';eta_omegaccc',1000,-5.,5.))
hvarscuts.append(root.TH1F('h_phi_omegaccc',';phi_omegaccc',1000,0.,10.))
hvarscuts.append(root.TH1F('h_rap_omegaccc',';rap_omegaccc',1000,-5.,5.))
hvarscuts.append(root.TH1F('h_inv_mass_omegacc',';inv_mass_omegacc',1000,3.,5.))
hvarscuts.append(root.TH1F('h_cos_p_omegacc',';cos_p_omegacc',1000,-1,1.))
hvarscuts.append(root.TH1F('h_cos_p_xy_omegacc',';cos_p_xy_omegacc',1000,-1.,1.))
hvarscuts.append(root.TH1F('h_decay_length_omegacc',';decay_length_omegacc',1000,0.,10.))
hvarscuts.append(root.TH1F('h_decay_length_xy_omegacc',';decay_length_xy_omegacc',1000,0.,10.))
hvarscuts.append(root.TH1F('h_chi2ndf_omegacc',';chi2ndf_omegacc',1000,0.,20.))
hvarscuts.append(root.TH1F('h_d0_omegacc',';d0_omegacc',1000,-1,1.))
hvarscuts.append(root.TH1F('h_pt_omegacc',';pt_omegacc',1000,0.,20.))
hvarscuts.append(root.TH1F('h_eta_omegacc',';eta_omegacc',1000,-5.,5.))
hvarscuts.append(root.TH1F('h_phi_omegacc',';phi_omegacc',1000,0.,10.))
hvarscuts.append(root.TH1F('h_rap_omegacc',';rap_omegacc',1000,-5.,5.))
hvarscuts.append(root.TH1F('h_inv_mass_omegac',';inv_mass_omegac',1000,2.,4.))
hvarscuts.append(root.TH1F('h_cos_p_omegac',';cos_p_omegac',1000,-1,1.))
hvarscuts.append(root.TH1F('h_cos_p_xy_omegac',';cos_p_xy_omegac',1000,-1.,1.))
hvarscuts.append(root.TH1F('h_decay_length_omegac',';decay_length_omegac',1000,0.,10.))
hvarscuts.append(root.TH1F('h_decay_length_xy_omegac',';decay_length_xy_omegac',1000,0.,10.))
hvarscuts.append(root.TH1F('h_chi2ndf_omegac',';chi2ndf_omegac',1000,0.,20.))
hvarscuts.append(root.TH1F('h_d0_omegac',';d0_omegac',1000,-1,1.))
hvarscuts.append(root.TH1F('h_pt_omegac',';pt_omegac',1000,0.,20.))
hvarscuts.append(root.TH1F('h_eta_omegac',';eta_omegac',1000,-5.,5.))
hvarscuts.append(root.TH1F('h_phi_omegac',';phi_omegac',1000,0.,10.))
hvarscuts.append(root.TH1F('h_rap_omegac',';rap_omegac',1000,-5.,5.))
hvarscuts.append(root.TH1F('h_norm_decay_length_omegaccc',';norm_decay_length_omegaccc',1000,0.,10.))
hvarscuts.append(root.TH1F('h_norm_decay_length_xy_omegaccc',';norm_decay_length_xy_omegaccc',1000,0.,10.))
#hvarscuts.append(root.TH1F('h_inv_mass_omega',';inv_mass_omega',1000,1.,2.))

hvarscuts_bkg = []
hvarscuts_bkg.append(root.TH1F('h_inv_mass_omegaccc_bkg',';inv_mass_omegaccc',1000,4.,6.))
hvarscuts_bkg.append(root.TH1F('h_cos_p_omegaccc_bkg',';cos_p_omegaccc',1000,-1,1.))
hvarscuts_bkg.append(root.TH1F('h_cos_p_xy_omegaccc_bkg',';cos_p_xy_omegaccc',1000,-1.,1.))
hvarscuts_bkg.append(root.TH1F('h_decay_length_omegaccc_bkg',';decay_length_omegaccc',1000,0.,10.))
hvarscuts_bkg.append(root.TH1F('h_decay_length_xy_omegaccc_bkg',';decay_length_xy_omegaccc',1000,0.,10.))
hvarscuts_bkg.append(root.TH1F('h_chi2ndf_omegaccc_bkg',';chi2ndf_omegaccc',1000,0.,20.))
hvarscuts_bkg.append(root.TH1F('h_d0_omegaccc_bkg',';d0_omegaccc',1000,-1,1.))
hvarscuts_bkg.append(root.TH1F('h_pt_omegaccc_bkg',';pt_omegaccc',1000,0.,20.))
hvarscuts_bkg.append(root.TH1F('h_eta_omegaccc_bkg',';eta_omegaccc',1000,-5.,5.))
hvarscuts_bkg.append(root.TH1F('h_phi_omegaccc_bkg',';phi_omegaccc',1000,0.,10.))
hvarscuts_bkg.append(root.TH1F('h_rap_omegaccc_bkg',';rap_omegaccc',1000,-5.,5.))
hvarscuts_bkg.append(root.TH1F('h_inv_mass_omegacc_bkg',';inv_mass_omegacc',1000,3.,5.))
hvarscuts_bkg.append(root.TH1F('h_cos_p_omegacc_bkg',';cos_p_omegacc',1000,-1,1.))
hvarscuts_bkg.append(root.TH1F('h_cos_p_xy_omegacc_bkg',';cos_p_xy_omegacc',1000,-1.,1.))
hvarscuts_bkg.append(root.TH1F('h_decay_length_omegacc_bkg',';decay_length_omegacc',1000,0.,10.))
hvarscuts_bkg.append(root.TH1F('h_decay_length_xy_omegacc_bkg',';decay_length_xy_omegacc',1000,0.,10.))
hvarscuts_bkg.append(root.TH1F('h_chi2ndf_omegacc_bkg',';chi2ndf_omegacc',1000,0.,20.))
hvarscuts_bkg.append(root.TH1F('h_d0_omegacc_bkg',';d0_omegacc',1000,-1,1.))
hvarscuts_bkg.append(root.TH1F('h_pt_omegacc_bkg',';pt_omegacc',1000,0.,20.))
hvarscuts_bkg.append(root.TH1F('h_eta_omegacc_bkg',';eta_omegacc',1000,-5.,5.))
hvarscuts_bkg.append(root.TH1F('h_phi_omegacc_bkg',';phi_omegacc',1000,0.,10.))
hvarscuts_bkg.append(root.TH1F('h_rap_omegacc_bkg',';rap_omegacc',1000,-5.,5.))
hvarscuts_bkg.append(root.TH1F('h_inv_mass_omegac_bkg',';inv_mass_omegac',1000,2.,4.))
hvarscuts_bkg.append(root.TH1F('h_cos_p_omegac_bkg',';cos_p_omegac',1000,-1,1.))
hvarscuts_bkg.append(root.TH1F('h_cos_p_xy_omegac_bkg',';cos_p_xy_omegac',1000,-1.,1.))
hvarscuts_bkg.append(root.TH1F('h_decay_length_omegac_bkg',';decay_length_omegac',1000,0.,10.))
hvarscuts_bkg.append(root.TH1F('h_decay_length_xy_omegac_bkg',';decay_length_xy_omegac',1000,0.,10.))
hvarscuts_bkg.append(root.TH1F('h_chi2ndf_omegac_bkg',';chi2ndf_omegac',1000,0.,20.))
hvarscuts_bkg.append(root.TH1F('h_d0_omegac_bkg',';d0_omegac',1000,-1,1.))
hvarscuts_bkg.append(root.TH1F('h_pt_omegac_bkg',';pt_omegac',1000,0.,20.))
hvarscuts_bkg.append(root.TH1F('h_eta_omegac_bkg',';eta_omegac',1000,-5.,5.))
hvarscuts_bkg.append(root.TH1F('h_phi_omegac_bkg',';phi_omegac',1000,0.,10.))
hvarscuts_bkg.append(root.TH1F('h_rap_omegac_bkg',';rap_omegac',1000,-5.,5.))
hvarscuts_bkg.append(root.TH1F('h_norm_decay_length_omegaccc_bkg',';norm_decay_length_omegaccc',1000,0.,10.))
hvarscuts_bkg.append(root.TH1F('h_norm_decay_length_xy_omegaccc_bkg',';norm_decay_length_xy_omegaccc',1000,0.,10.))
#hvarscuts_bkg.append(root.TH1F('h_inv_mass_omega_bkg',';inv_mass_omega',1000,1.,2.))


counter_evt = -1
for entry in treecutvar:
    if entry.fIsSignal_omegaccc==True:
        hvarscuts[0].Fill(entry.fInvMass_omegaccc)
        hvarscuts[1].Fill(entry.fCosPA_omegaccc)
        hvarscuts[2].Fill(entry.fCosPAXY_omegaccc)
        hvarscuts[3].Fill(entry.fDecayLength_omegaccc)
        hvarscuts[4].Fill(entry.fDecayLengthXY_omegaccc)
        hvarscuts[5].Fill(entry.fChi2ndf_omegaccc)
        hvarscuts[6].Fill(entry.fImpParRPhi_omegaccc)
        hvarscuts[7].Fill(entry.fPt_omegaccc)
        hvarscuts[8].Fill(entry.fEta_omegaccc)
        hvarscuts[9].Fill(entry.fPhi_omegaccc)
        hvarscuts[10].Fill(entry.fRap_omegaccc)
        hvarscuts[11].Fill(entry.fInvMass_omegacc)
        hvarscuts[12].Fill(entry.fCosPA_omegacc)
        hvarscuts[13].Fill(entry.fCosPAXY_omegacc)
        hvarscuts[14].Fill(entry.fDecayLength_omegacc)
        hvarscuts[15].Fill(entry.fDecayLengthXY_omegacc)
        hvarscuts[16].Fill(entry.fChi2ndf_omegacc)
        hvarscuts[17].Fill(entry.fImpParRPhi_omegacc)
        hvarscuts[18].Fill(entry.fPt_omegacc)
        hvarscuts[19].Fill(entry.fEta_omegacc)
        hvarscuts[20].Fill(entry.fPhi_omegacc)
        hvarscuts[21].Fill(entry.fRap_omegacc)
        hvarscuts[22].Fill(entry.fInvMass_omegac)
        hvarscuts[23].Fill(entry.fCosPA_omegac)
        hvarscuts[24].Fill(entry.fCosPAXY_omegac)
        hvarscuts[25].Fill(entry.fDecayLength_omegac)
        hvarscuts[26].Fill(entry.fDecayLengthXY_omegac)
        hvarscuts[27].Fill(entry.fChi2ndf_omegac)
        hvarscuts[28].Fill(entry.fImpParRPhi_omegac)
        hvarscuts[29].Fill(entry.fPt_omegac)
        hvarscuts[30].Fill(entry.fEta_omegac)
        hvarscuts[31].Fill(entry.fPhi_omegac)
        hvarscuts[32].Fill(entry.fRap_omegac)
        hvarscuts[33].Fill(entry.fNormDecayLength_omegaccc)
        hvarscuts[34].Fill(entry.fNormDecayLengthXY_omegaccc)
#    if entry.fIsSignal==False:
#        hvarscuts[34].Fill(entry.fInvMass_omega)
#        hvarscuts[35].Fill(entry.fInvMass_omegaccc)
#        hvarscuts[36].Fill(entry.fInvMass_omegacc)
#        hvarscuts[37].Fill(entry.fInvMass_omegac)
for entry in treecutvar_bkg:
    if entry.fIsSignal_omegaccc==False:
        hvarscuts_bkg[0].Fill(entry.fInvMass_omegaccc)
        hvarscuts_bkg[1].Fill(entry.fCosPA_omegaccc)
        hvarscuts_bkg[2].Fill(entry.fCosPAXY_omegaccc)
        hvarscuts_bkg[3].Fill(entry.fDecayLength_omegaccc)
        hvarscuts_bkg[4].Fill(entry.fDecayLengthXY_omegaccc)
        hvarscuts_bkg[5].Fill(entry.fChi2ndf_omegaccc)
        hvarscuts_bkg[6].Fill(entry.fImpParRPhi_omegaccc)
        hvarscuts_bkg[7].Fill(entry.fPt_omegaccc)
        hvarscuts_bkg[8].Fill(entry.fEta_omegaccc)
        hvarscuts_bkg[9].Fill(entry.fPhi_omegaccc)
        hvarscuts_bkg[10].Fill(entry.fRap_omegaccc)
        hvarscuts_bkg[11].Fill(entry.fInvMass_omegacc)
        hvarscuts_bkg[12].Fill(entry.fCosPA_omegacc)
        hvarscuts_bkg[13].Fill(entry.fCosPAXY_omegacc)
        hvarscuts_bkg[14].Fill(entry.fDecayLength_omegacc)
        hvarscuts_bkg[15].Fill(entry.fDecayLengthXY_omegacc)
        hvarscuts_bkg[16].Fill(entry.fChi2ndf_omegacc)
        hvarscuts_bkg[17].Fill(entry.fImpParRPhi_omegacc)
        hvarscuts_bkg[18].Fill(entry.fPt_omegacc)
        hvarscuts_bkg[19].Fill(entry.fEta_omegacc)
        hvarscuts_bkg[20].Fill(entry.fPhi_omegacc)
        hvarscuts_bkg[21].Fill(entry.fRap_omegacc)
        hvarscuts_bkg[22].Fill(entry.fInvMass_omegac)
        hvarscuts_bkg[23].Fill(entry.fCosPA_omegac)
        hvarscuts_bkg[24].Fill(entry.fCosPAXY_omegac)
        hvarscuts_bkg[25].Fill(entry.fDecayLength_omegac)
        hvarscuts_bkg[26].Fill(entry.fDecayLengthXY_omegac)
        hvarscuts_bkg[27].Fill(entry.fChi2ndf_omegac)
        hvarscuts_bkg[28].Fill(entry.fImpParRPhi_omegac)
        hvarscuts_bkg[29].Fill(entry.fPt_omegac)
        hvarscuts_bkg[30].Fill(entry.fEta_omegac)
        hvarscuts_bkg[31].Fill(entry.fPhi_omegac)
        hvarscuts_bkg[32].Fill(entry.fRap_omegac)
        hvarscuts_bkg[33].Fill(entry.fNormDecayLength_omegaccc)
        hvarscuts_bkg[34].Fill(entry.fNormDecayLengthXY_omegaccc)

pdffilename = 'var_comp_omegaccc_logy.pdf'

nvars = len(hvarscuts)
canvas = []
for ivar in range(nvars):
  canvas.append(root.TCanvas('canvas%d' % ivar,'',800,800))
  canvas[ivar].cd().SetLogy()
  hvarscuts[ivar].SetLineColor(2)
  hvarscuts_bkg[ivar].SetLineColor(4)
  if hvarscuts[ivar].Integral()!=0:
    hvarscuts[ivar].Scale(1./hvarscuts[ivar].Integral())
  if hvarscuts_bkg[ivar].Integral()!=0:
    hvarscuts_bkg[ivar].Scale(1./hvarscuts_bkg[ivar].Integral())
  hvarscuts[ivar].Draw('hist')
  hvarscuts_bkg[ivar].Draw('histsame')
  if ivar==0:
    canvas[ivar].Print('%s[' % pdffilename)
  canvas[ivar].Print('%s' % pdffilename)
  if ivar==nvars-1:
    canvas[ivar].Print('%s]' % pdffilename)

input("Type enter to exit")
